"""Server-side trading performance and discipline.

The discipline score and the performance breakdowns were computed in the browser
(manual-trading/frontend/src/discipline.ts, ManualStatsPage.tsx). A graduation
gate cannot trust numbers computed on the client, so this is the server's copy.

`compute_discipline` is a FAITHFUL PORT of computeDisciplineScore in
discipline.ts (same four components, weights, windowing and rounding), guarded
by golden fixtures produced by running the real TypeScript
(tests/fixtures/discipline_golden.json, regenerated by
tests/fixtures/gen_discipline_golden.mjs). If the formula changes in the
frontend, regenerate the fixtures and update this file. The formula is now
duplicated in three places (discipline.ts, the shell badge in shell/index.html,
and here); the new web app in Phase 2 should read it from the server only.

Scope: a user's OWN manual paper trades (strategy_id IS NULL), one segment, and
by default only the CURRENT equity curve (from the latest reset marker), so a
reset restarts the record instead of hiding earlier results. Figures are net of
Indian charges and slippage where the account applied them (pnl already is);
charges and slippage are also reported separately so the cost is visible.
"""

import math
from dataclasses import dataclass, field, replace
from datetime import date, datetime
from typing import Optional
from zoneinfo import ZoneInfo

from sqlalchemy.orm import Session

from app.adapters.db import models as db_models
from app.config import settings

MIN_TRADES_FOR_SCORE = 5
DISCIPLINE_WEIGHTS = {"planned": 1, "planAdherence": 2, "planReview": 2, "outcome": 1}


@dataclass
class TradeRecord:
    """One closed manual trade (a single position, or a whole option group)."""

    segment: str
    symbol: str
    pnl: Optional[float]
    entry_price: Optional[float]
    stop_loss_price: Optional[float]
    target_price: Optional[float]
    quantity: Optional[float]
    exit_time: datetime
    exit_reason: Optional[str]
    order_type: Optional[str]
    entry_setup_tag: Optional[str]
    entry_confidence: Optional[int]
    setup_tag: Optional[str]
    confidence: Optional[int]
    reviewed: bool
    auto_traded: bool
    charges: float = 0.0
    slippage_cost: float = 0.0
    # True when Indian charges were recorded for this trade (charges is not NULL), i.e. its P&L is
    # net of costs. A gross trade cannot count toward the paper track record (app/domain/track_record.py).
    costs_applied: bool = False
    # True for a trade placed through the live broker; a paper trade is False. Reported separately, never mixed.
    live: bool = False
    # For the post-session summary: which way, where it ended, when it opened, and a short name ("naked call").
    side: Optional[str] = None
    exit_price: Optional[float] = None
    entry_time: Optional[datetime] = None
    label: Optional[str] = None
    # Rupees per unit of this trade's own currency: 1 for NSE/MCX, the USD/INR rate it closed at for CRYPTO. pnl, charges and slippage_cost stay in the
    # trade's own currency (so the R multiple, a ratio against its dollar entry and stop, is right); the totals are converted with this.
    fx: float = 1.0

    @property
    def pnl_inr(self) -> Optional[float]:
        return self.pnl * self.fx if self.pnl is not None else None


def day_key(moment: datetime) -> date:
    return moment.astimezone(ZoneInfo(settings.equity_history_timezone)).date()


# --- discipline (port of discipline.ts) ---------------------------------------------------------------------


def _mean(values: list[float]) -> dict:
    if not values:
        return {"rate": None, "trades": 0}
    return {"rate": sum(values) / len(values), "trades": len(values)}


def _realized_r(t: TradeRecord) -> Optional[float]:
    if t.pnl is None or t.entry_price is None or t.stop_loss_price is None or t.quantity is None:
        return None
    if t.entry_price == t.stop_loss_price:
        return None
    risk = abs(t.entry_price - t.stop_loss_price) * t.quantity
    return t.pnl / risk if risk > 0 else None


def _has_plan(t: TradeRecord) -> bool:
    return t.order_type == "limit" and t.stop_loss_price is not None


def _declared_before(t: TradeRecord) -> bool:
    return t.entry_setup_tag is not None and t.entry_setup_tag != "" and t.entry_confidence is not None


def _reviewed_after(t: TradeRecord) -> bool:
    return t.reviewed and t.setup_tag is not None and t.setup_tag != "" and t.confidence is not None


def _window(trades: list[TradeRecord], days: int) -> tuple[list[TradeRecord], Optional[str]]:
    """Walk back from the most recent trade collecting whole calendar days that
    actually had a trade until `days` distinct ones are found - a rolling window
    measured in days-with-activity, so a quiet stretch does not dilute it."""
    if not trades:
        return [], None
    ordered = sorted(trades, key=lambda t: t.exit_time, reverse=True)
    active: list[date] = []
    seen: set[date] = set()
    for t in ordered:
        k = day_key(t.exit_time)
        if k not in seen:
            seen.add(k)
            active.append(k)
            if len(active) >= days:
                break
    cutoff = set(active)
    return [t for t in ordered if day_key(t.exit_time) in cutoff], active[-1].isoformat() if active else None


def _js_round(x: float) -> int:
    """Math.round: halves round toward +infinity (Python's round() is banker's)."""
    return int(math.floor(x + 0.5))


def compute_discipline(all_trades: list[TradeRecord], days: int) -> dict:
    trades = [t for t in all_trades if not t.auto_traded]
    windowed, window_start = _window(trades, days)

    planned = _mean([1.0 if _has_plan(t) else 0.0 for t in windowed])
    plan_adherence = _mean([0.0 if not _has_plan(t) else (0.4 if t.exit_reason == "manual" else 1.0) for t in windowed])

    before_flags = [1.0 if _declared_before(t) else 0.0 for t in windowed]
    after_flags = [1.0 if _reviewed_after(t) else 0.0 for t in windowed]
    plan_review = {
        **_mean([0.5 * (1.0 if _declared_before(t) else 0.0) + 0.5 * (1.0 if _reviewed_after(t) else 0.0) for t in windowed]),
        "beforeRate": sum(before_flags) / len(before_flags) if before_flags else None,
        "afterRate": sum(after_flags) / len(after_flags) if after_flags else None,
    }

    with_pnl = [t for t in windowed if t.pnl is not None]
    win_rate = (sum(1 for t in with_pnl if t.pnl > 0) / len(with_pnl)) if with_pnl else None
    r_values = [r for r in (_realized_r(t) for t in windowed) if r is not None]
    avg_r = sum(r_values) / len(r_values) if r_values else None
    outcome_rate: Optional[float] = None
    if win_rate is not None and avg_r is not None:
        outcome_rate = 0.5 * win_rate + 0.5 * max(0.0, min(1.0, avg_r / 2))
    elif win_rate is not None:
        outcome_rate = win_rate
    outcome = {"rate": outcome_rate, "trades": len(with_pnl), "winRate": win_rate, "avgR": avg_r}

    parts = []
    for key, comp in (("planned", planned), ("planAdherence", plan_adherence), ("planReview", plan_review), ("outcome", outcome)):
        if comp["rate"] is not None:
            parts.append((comp["rate"], DISCIPLINE_WEIGHTS[key]))
    total_w = sum(w for _, w in parts)
    score = _js_round(sum(r * w for r, w in parts) / total_w * 100) if len(windowed) >= MIN_TRADES_FOR_SCORE and total_w > 0 else None

    return {
        "score": score,
        "windowDays": days,
        "windowStart": window_start,
        "tradeCount": len(windowed),
        "planned": planned,
        "planAdherence": plan_adherence,
        "planReview": plan_review,
        "outcome": outcome,
    }


# --- performance (new; the browser page computed these ad hoc) -------------------------------------------------


@dataclass(frozen=True)
class PerformanceStats:
    trades: int
    wins: int
    losses: int
    breakeven: int
    win_rate_pct: Optional[float]
    total_pnl: float  # net of charges and slippage where the account applied them
    gross_pnl: float  # before those costs (total_pnl + charges + slippage)
    total_charges: float
    total_slippage: float
    avg_pnl: Optional[float]  # also the per-trade expectancy
    avg_win: Optional[float]
    avg_loss: Optional[float]
    profit_factor: Optional[float]  # gross wins / gross losses; None when there are no losses
    avg_r: Optional[float]  # realized R over trades that had a stop (spot/future); options excluded
    best_trade: Optional[float]
    worst_trade: Optional[float]
    max_consecutive_losses: int


def compute_performance(trades: list[TradeRecord]) -> Optional[PerformanceStats]:
    """None when there is nothing with a P&L. Trades are considered in exit
    order for the losing-streak figure."""
    own = sorted((t for t in trades if t.pnl is not None), key=lambda t: t.exit_time)
    if not own:
        return None
    r_values = [r for r in (_realized_r(t) for t in own) if r is not None]  # a ratio: in the trade's own currency
    # Everything else is money, in rupees.
    counted = [replace(t, pnl=t.pnl * t.fx, charges=t.charges * t.fx, slippage_cost=t.slippage_cost * t.fx) for t in own]
    wins = [t.pnl for t in counted if t.pnl > 0]
    losses = [t.pnl for t in counted if t.pnl < 0]
    total = sum(t.pnl for t in counted)
    charges = sum(t.charges for t in counted)
    slippage = sum(t.slippage_cost for t in counted)
    streak = worst_streak = 0
    for t in counted:
        streak = streak + 1 if t.pnl < 0 else 0
        worst_streak = max(worst_streak, streak)
    gross_loss = abs(sum(losses))
    return PerformanceStats(
        trades=len(counted),
        wins=len(wins),
        losses=len(losses),
        breakeven=len(counted) - len(wins) - len(losses),
        win_rate_pct=len(wins) / len(counted) * 100.0,
        total_pnl=total,
        gross_pnl=total + charges + slippage,
        total_charges=charges,
        total_slippage=slippage,
        avg_pnl=total / len(counted),
        avg_win=sum(wins) / len(wins) if wins else None,
        avg_loss=sum(losses) / len(losses) if losses else None,
        profit_factor=(sum(wins) / gross_loss) if gross_loss > 0 else None,
        avg_r=sum(r_values) / len(r_values) if r_values else None,
        best_trade=max(t.pnl for t in counted),
        worst_trade=min(t.pnl for t in counted),
        max_consecutive_losses=worst_streak,
    )


# --- loading -----------------------------------------------------------------------------------------------------


def _side(action) -> Optional[str]:
    a = (action or "").strip().upper()
    return "long" if a == "BUY" else "short" if a == "SELL" else None


def _reviewed(reviewed_at, notes) -> bool:
    return reviewed_at is not None or (notes is not None and notes.strip() != "")


def _f(value) -> Optional[float]:
    return float(value) if value is not None else None


def load_manual_trades(db: Session, user_id, segment: str, since: Optional[date] = None, book: str = "intraday") -> list[TradeRecord]:
    """The caller's own closed MANUAL trades for one segment (strategy_id IS
    NULL, the same "manual only" the frontend pages use): single positions that
    are not option legs, plus whole option groups. `since` (an IST date) drops
    trades that closed before it.

    `book` picks which of the user's two paper balances the trades belong to: 'intraday' (everything that is not a multi-day hold,
    the default) or 'positional' (spot holds with horizon='positional'; an option group is never positional)."""
    from app.domain.position_manager import load_settings  # local: position_manager is a heavy module and nothing else here needs it

    P, G = db_models.Position, db_models.OptionPositionGroup
    current_rate = load_settings(db, user_id).usdinr_rate if segment == "CRYPTO" else None

    def fx_of(row) -> float:
        if segment != "CRYPTO":
            return 1.0
        closed_at = getattr(row, "usdinr_at_close", None)
        rate = float(closed_at) if closed_at is not None else current_rate
        return rate if rate is not None else 1.0

    positional = book == "positional"
    positions = (
        db.query(P)
        .filter(
            P.user_id == user_id, P.strategy_id.is_(None), P.status == "CLOSED", P.segment == segment, P.option_group_id.is_(None), P.exit_time.isnot(None),
            P.horizon == "positional" if positional else P.horizon != "positional",
        )
        .all()
    )
    groups = (
        []
        if positional
        else db.query(G)
        .filter(G.user_id == user_id, G.strategy_id.is_(None), G.status == "CLOSED", G.segment == segment, G.exit_time.isnot(None))
        .all()
    )
    # A spread is live when any of its legs went to the broker.
    live_groups = (
        {leg.option_group_id for leg in db.query(P).filter(P.user_id == user_id, P.option_group_id.isnot(None), P.is_live_broker_order.is_(True)).all()}
        if groups
        else set()
    )
    records = [
        TradeRecord(
            segment=p.segment, symbol=p.symbol, pnl=_f(p.pnl), entry_price=_f(p.entry_price), stop_loss_price=_f(p.stop_loss_price),
            target_price=_f(p.target_price), quantity=_f(p.quantity), exit_time=p.exit_time, exit_reason=p.exit_reason,
            order_type=p.order_type, entry_setup_tag=p.entry_setup_tag, entry_confidence=p.entry_confidence, setup_tag=p.setup_tag,
            confidence=p.confidence, reviewed=_reviewed(p.reviewed_at, p.notes), auto_traded=bool(p.auto_traded),
            charges=_f(p.charges) or 0.0, slippage_cost=_f(p.slippage_cost) or 0.0, costs_applied=p.charges is not None,
            live=bool(p.is_live_broker_order), fx=fx_of(p),
            side=_side(getattr(p, "action", None)), exit_price=_f(getattr(p, "exit_price", None)), entry_time=getattr(p, "entry_time", None),
        )
        for p in positions
    ] + [
        TradeRecord(
            segment=g.segment, symbol=g.underlying_symbol, pnl=_f(g.pnl), entry_price=None, stop_loss_price=_f(g.spot_stop_loss_price),
            target_price=_f(g.spot_target_price), quantity=_f(g.quantity), exit_time=g.exit_time, exit_reason=g.exit_reason,
            order_type=g.order_type, entry_setup_tag=g.entry_setup_tag, entry_confidence=g.entry_confidence, setup_tag=g.setup_tag,
            confidence=g.confidence, reviewed=_reviewed(g.reviewed_at, g.notes), auto_traded=bool(g.auto_traded),
            charges=_f(g.charges) or 0.0, slippage_cost=_f(g.slippage_cost) or 0.0, costs_applied=g.charges is not None,
            live=g.id in live_groups, fx=fx_of(g),
            side=_side(getattr(g, "action", None)), entry_time=getattr(g, "created_at", None), label=getattr(g, "strategy_type", None),
        )
        for g in groups
    ]
    if since is not None:
        records = [r for r in records if day_key(r.exit_time) >= since]
    return records


def epoch_start(db: Session, account) -> Optional[date]:
    """The IST date of the account's latest reset marker (see equity_history.py),
    or None if it has never been reset."""
    S = db_models.AccountEquitySnapshot
    row = (
        db.query(S).filter(S.account_id == account.id, S.is_reset_point.is_(True)).order_by(S.snapshot_date.desc()).first()
    )
    return row.snapshot_date if row is not None else None
