"""Publishing a note as an "idea" to a Telegram channel or group, through a SEPARATE bot (settings.telegram_ideas_bot_token) from the
private alerts bot.

Who and what, by design:
  * Only an admin (the operator) publishes, to one destination the operator sets. It is not offered to other users.
  * Only "plan" and "observation" notes can be published; "mistake" and "review" are private by nature.
  * Every post ends with a disclaimer, appended HERE on the server, so no client, preview or code path can send a post without it.
    The wording is configurable (IDEAS_DISCLAIMER) and an optional registration line (IDEAS_REGISTRATION_LINE, for example a SEBI
    registration number) is appended after it; the default is a general "not advice" notice and should be reviewed by counsel
    before the audience widens - it does not assert any registration status.
  * The context line is built from an allow-list of the note's market context (price, regime, trend, PCR). The position held
    (`holding`) and the AI read are NEVER published, whatever the client sends.
  * A CLOSED trade can be attached (never an open one: entry, stop and target for a trade still running read as a live call). Only
    its side, instrument, entry / stop / target, exit and result are shown, and the result is in R (price move over the risk taken)
    or, for an option spread, a percentage of the premium paid (after charges, as the app records it; a position's is before): never a
    quantity, a lot count, a rupee amount, the charges themselves or any balance. Every trade is labelled paper or live, because a paper result presented unlabelled would mislead anyone following it.
  * An AI analysis of the stock (the Scan page's "AI analysis": its chart and business reads and one verdict over both) can be attached. Only
    the fields of `Analysis` below exist, each is trimmed to a short length, and the server writes the section itself, ending with a line saying
    it is generated by AI and simple rules from public data and can be wrong: the client sends facts, never the wording of the post.
  * Each note is published once; it can be unpublished (the message is deleted) and then published again.
"""

from __future__ import annotations

import base64
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from sqlalchemy.orm import Session

from app.adapters.db.models import IdeasDestination, PublishedIdea
from app.config import settings
from app.domain import telegram_api

PUBLISHABLE_TAGS = ("plan", "observation")
NOTE_MAX = 500
CAPTION_MAX = 1024  # Telegram's limit for a photo caption
MESSAGE_MAX = 4096
MAX_IMAGE_BYTES = 4_000_000

DEFAULT_DISCLAIMER = (
    "Disclaimer: Personal study note shared for education and information only. Not investment advice, a recommendation, or an "
    "offer to buy or sell any security or derivative. Markets involve risk, including loss of capital; past performance does not "
    "indicate future results. Do your own research or consult a SEBI-registered adviser before acting."
)

_REGIME_WORD = {"trending_up": "Trending up", "trending_down": "Trending down", "ranging": "Ranging", "transitional": "Changing"}


class IdeaError(Exception):
    """A refusal or failure with a status code and a message the person can act on."""

    def __init__(self, status: int, detail: str):
        super().__init__(detail)
        self.status, self.detail = status, detail


@dataclass
class Trade:
    """The only things published about a trade. There is deliberately no field for quantity, lots, capital, rupee P&L or charges, so
    none of them can reach a post. `kind` "group" is an option spread, whose entry/stop/target are levels on the UNDERLYING."""

    kind: str  # "position" | "group"
    label: str
    side: str  # "BUY" | "SELL"
    live: bool
    entry: Optional[float]
    stop: Optional[float]
    target: Optional[float]
    exit: Optional[float] = None  # a position's exit price
    exit_reason: Optional[str] = None
    result_pct: Optional[float] = None  # a spread's result as a percentage of the premium paid


@dataclass
class AnalysisLevel:
    low: float
    high: float
    distance_pct: float  # how far the zone is from the price, as a percentage of the price


@dataclass
class Analysis:
    """The only things published from an AI analysis. Short on purpose: a post is read in a chat, not studied."""

    verdict: str  # the one-line headline
    agreement: str  # aligned | mixed | conflicting | technical_only
    overall: str  # bullish | bearish | neutral
    overall_strength: Optional[str]  # strong | moderate | slight
    chart_bias: str
    chart_points: list[str]
    price: Optional[float] = None
    as_of: Optional[str] = None  # an ISO date
    business_bias: Optional[str] = None
    business_confidence: Optional[float] = None  # 0 to 1: the AI's own confidence in its read of the page
    business_summary: Optional[str] = None
    pros: Optional[list[str]] = None
    cons: Optional[list[str]] = None
    support: Optional[AnalysisLevel] = None
    resistance: Optional[AnalysisLevel] = None


@dataclass
class Idea:
    note_id: UUID
    segment: str
    symbol: str
    interval: Optional[str]
    tag: str
    text: str
    context: Optional[dict]
    include_context: bool
    image: Optional[bytes]
    trade: Optional[Trade] = None
    analysis: Optional[Analysis] = None


def disclaimer() -> str:
    text = (settings.ideas_disclaimer or "").strip() or DEFAULT_DISCLAIMER
    reg = (settings.ideas_registration_line or "").strip()
    return f"{text}\n{reg}" if reg else text


def _num(v) -> Optional[float]:
    return float(v) if isinstance(v, (int, float)) and not isinstance(v, bool) else None


def context_line(ctx: Optional[dict]) -> str:
    """What the market looked like, from the allow-list only. Anything else in `ctx` (holding, ai_read, oi buildup...) is ignored."""
    if not isinstance(ctx, dict):
        return ""
    parts = []
    price = _num(ctx.get("price"))
    if price is not None:
        parts.append(f"Price {price:,.2f}")
    regime = ctx.get("regime")
    if isinstance(regime, dict) and isinstance(regime.get("regime"), str):
        adx = _num(regime.get("adx"))
        parts.append(_REGIME_WORD.get(regime["regime"], regime["regime"]) + (f" · ADX {adx:.0f}" if adx is not None else ""))
    trend = ctx.get("structure_trend")
    if isinstance(trend, dict):
        for tf, t in trend.items():
            if isinstance(tf, str) and isinstance(t, str) and len(tf) <= 8 and len(t) <= 12:
                parts.append(f"{tf} {'sideways' if t == 'range' else t}")
    oi = ctx.get("oi")
    pcr = _num(oi.get("pcr")) if isinstance(oi, dict) else None
    if pcr is not None:
        parts.append(f"PCR {pcr:.2f}")
    return " · ".join(parts)


_EXIT_WORDS = {
    "target": "hit the target", "target_hit": "hit the target", "stop_loss": "stopped out", "stop_loss_hit": "stopped out", "stop": "stopped out",
    "trailing_stop": "stopped out on the trail", "square_off": "squared off at the end of the day", "counter_signal": "closed on a counter signal",
    "manual": "closed by hand", "indicator_exit": "closed on its exit rule", "exit_condition": "closed on its exit rule",
}


def _price(v: float) -> str:
    return f"{v:,.2f}"


def _signed(v: float, decimals: int, suffix: str) -> str:
    if round(v, decimals) == 0:
        return f"{0:.{decimals}f}{suffix}"
    return f"{'+' if v > 0 else '−'}{abs(v):.{decimals}f}{suffix}"


def trade_result(t: Trade) -> Optional[str]:
    """How the trade ended, quantity-free. A position: in R (the move over the risk taken) when it had a stop, otherwise as a percentage
    move. A spread: a percentage of the premium paid. Before charges."""
    if t.kind == "group":
        return f"{_signed(t.result_pct, 0, '%')} of the premium paid" if t.result_pct is not None else None
    if t.entry is None or t.exit is None:
        return None
    sign = 1 if t.side == "BUY" else -1
    move = (t.exit - t.entry) * sign
    if t.stop is not None and t.stop != t.entry:
        return _signed(move / abs(t.entry - t.stop), 1, "R")
    return _signed(move / t.entry * 100, 1, "%")


def planned_risk_reward(t: Trade) -> Optional[float]:
    if None in (t.entry, t.stop, t.target) or t.stop == t.entry:
        return None
    return abs(t.target - t.entry) / abs(t.entry - t.stop)


def trade_block(t: Trade) -> str:
    """One line about an attached closed trade: what it was, the levels, how it ended, and whether it was paper or live."""
    under = "Underlying " if t.kind == "group" else ""
    parts = [f"{t.side} {t.label}"]
    if t.entry is not None:
        parts.append(f"{under}entry {_price(t.entry)}")
    if t.stop is not None:
        parts.append(f"{under}stop {_price(t.stop)}")
    if t.target is not None:
        parts.append(f"{under}target {_price(t.target)}")
    rr = planned_risk_reward(t)
    if rr is not None:
        parts.append(f"R:R {rr:.1f}")
    if t.kind == "position" and t.exit is not None:
        reason = _EXIT_WORDS.get((t.exit_reason or "").lower())
        parts.append(f"exit {_price(t.exit)}" + (f" ({reason})" if reason else ""))
    elif t.kind == "group":
        reason = _EXIT_WORDS.get((t.exit_reason or "").lower())
        if reason:
            parts.append(f"closed: {reason}")
    result = trade_result(t)
    if result:
        # A position's result comes from its prices, so it is before charges; a spread's comes from its stored P&L, which the app
        # records after charges and slippage. Each says which it is.
        parts.append(f"{result} ({'after' if t.kind == 'group' else 'before'} charges)")
    return f"{'Live' if t.live else 'Paper'} trade: " + " · ".join(parts)


def check_trade(t: Trade) -> None:
    """Only a CLOSED trade can be attached. The request carries no 'open' state, so a trade is closed only if it says how it ended."""
    if t.kind == "position" and (t.exit is None or t.entry is None):
        raise IdeaError(422, "Only a closed trade can be attached: this one has no exit price.")
    if t.kind == "group" and t.result_pct is None:
        raise IdeaError(422, "Only a closed trade can be attached: this one has no result.")
    if t.kind not in ("position", "group") or t.side not in ("BUY", "SELL"):
        raise IdeaError(422, "That trade could not be read.")


_ARROW = {"bullish": "▲", "bearish": "▼", "neutral": "◆"}
_AGREEMENT_WORDS = {
    "aligned": "chart and business agree", "mixed": "only one side leans", "conflicting": "chart and business disagree", "technical_only": "chart only",
}
ANALYSIS_NOTICE = "Generated by AI and simple rules from public data; it can be wrong."


def _clip(text: str, n: int) -> str:
    """One line, no control characters, at most n characters (ending in an ellipsis when cut)."""
    text = re.sub(r"\s+", " ", re.sub(r"[\x00-\x1f\x7f]", " ", text or "")).strip()
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def _bias(b: Optional[str]) -> str:
    return f"{_ARROW.get(b or '', '◆')} {b or 'neutral'}"


def _level(label: str, lv: AnalysisLevel, sign: str) -> str:
    return f"{label} {_price(lv.low)}–{_price(lv.high)} ({sign}{abs(lv.distance_pct):.1f}%)"


def analysis_block(a: Analysis) -> str:
    """The analysis as the post shows it: the verdict, the chart's lean and its first reasons, the business's lean and a line on it, the
    strongest points either way, the nearest levels, and a notice that it is machine-made. Written here from the fields, never sent as text."""
    when = ""
    if a.price is not None:
        when = f" · price {_price(a.price)}"
        if a.as_of:
            when += f" ({_clip(a.as_of, 12)})"
    lines = [f"🔎 AI analysis{when}"]
    overall = f"overall {_bias(a.overall)}" + (f" ({_clip(a.overall_strength, 10)})" if a.overall_strength else "")
    lines.append(f"Verdict: {_clip(a.verdict, 120)}. {_AGREEMENT_WORDS.get(a.agreement, '').capitalize()} · {overall}.")
    points = " · ".join(_clip(p, 90) for p in a.chart_points[:3] if p and p.strip())
    lines.append(f"Chart {_bias(a.chart_bias)}" + (f": {points}" if points else ""))
    if a.business_bias:
        sure = f" ({a.business_confidence * 100:.0f}% sure)" if a.business_confidence is not None and 0 <= a.business_confidence <= 1 else ""
        summary = f": {_clip(a.business_summary, 200)}" if a.business_summary else ""
        lines.append(f"Business {_bias(a.business_bias)}{sure}{summary}")
        pros = [_clip(p, 90) for p in (a.pros or [])[:2] if p and p.strip()]
        cons = [_clip(c, 90) for c in (a.cons or [])[:2] if c and c.strip()]
        if pros:
            lines.append("✓ " + " · ".join(pros))
        if cons:
            lines.append("✕ " + " · ".join(cons))
    levels = [x for x in (_level("resistance", a.resistance, "+") if a.resistance else None, _level("support", a.support, "−") if a.support else None) if x]
    if levels:
        lines.append("Nearby: " + " · ".join(levels))
    lines.append(ANALYSIS_NOTICE)
    return "\n".join(lines)


def _interval_word(interval: Optional[str]) -> str:
    return interval.replace("min", "m") if interval else ""


def header(idea: Idea) -> str:
    return " · ".join(p for p in (f"💡 {idea.symbol}", _interval_word(idea.interval), idea.tag) if p)


def build_text(idea: Idea) -> str:
    """The whole post as text: header, the note, the market line (if asked for) and the disclaimer."""
    blocks = [header(idea), idea.text.strip()]
    if idea.analysis is not None:
        blocks.append(analysis_block(idea.analysis))
    if idea.trade is not None:
        blocks.append(trade_block(idea.trade))
    if idea.include_context:
        line = context_line(idea.context)
        if line:
            blocks.append(line)
    blocks.append(disclaimer())
    return "\n\n".join(blocks)


@dataclass
class Plan:
    """How the post goes out: one text message, one photo with the whole post as its caption, or (when that would not fit a caption)
    a photo captioned with the header followed by the full text."""

    messages: list[tuple[str, str]]  # ("text" | "photo", body)
    text: str


def plan_post(idea: Idea) -> Plan:
    text = build_text(idea)
    if len(text) > MESSAGE_MAX:
        raise IdeaError(422, "That post is too long for Telegram.")
    if idea.image is None:
        return Plan([("text", text)], text)
    if len(text) <= CAPTION_MAX:
        return Plan([("photo", text)], text)
    return Plan([("photo", header(idea)), ("text", text)], text)


def decode_image(data: Optional[str]) -> Optional[bytes]:
    """A chart snapshot sent as base64 (with or without a data: URL prefix). None when there is none; 422 when it is not a PNG."""
    if not data:
        return None
    raw = re.sub(r"^data:image/[a-z]+;base64,", "", data.strip())
    try:
        png = base64.b64decode(raw, validate=True)
    except ValueError:
        raise IdeaError(422, "The chart snapshot could not be read.")
    if not png.startswith(b"\x89PNG"):
        raise IdeaError(422, "The chart snapshot is not a PNG image.")
    if len(png) > MAX_IMAGE_BYTES:
        raise IdeaError(422, "The chart snapshot is too large to send.")
    return png


def check_publishable(idea: Idea) -> None:
    if idea.tag not in PUBLISHABLE_TAGS:
        raise IdeaError(422, f"Only {' and '.join(PUBLISHABLE_TAGS)} notes can be published; '{idea.tag}' notes stay private.")
    if idea.trade is not None:
        check_trade(idea.trade)
    if idea.analysis is not None and not idea.analysis.verdict.strip():
        raise IdeaError(422, "The AI analysis has no verdict to show.")
    text = idea.text.strip()
    if not text:
        raise IdeaError(422, "The note is empty.")
    if len(text) > NOTE_MAX:
        raise IdeaError(422, f"The note is longer than {NOTE_MAX} characters.")


def destination(db: Session) -> Optional[str]:
    row = db.get(IdeasDestination, 1)
    return row.telegram_chat_id if row else None


def _ready(db: Session) -> tuple[str, str]:
    token = settings.telegram_ideas_bot_token
    if not token:
        raise IdeaError(503, "The ideas bot is not set up on this server (TELEGRAM_IDEAS_BOT_TOKEN).")
    chat = destination(db)
    if not chat:
        raise IdeaError(400, "Set the ideas channel first.")
    return token, chat


def get_published(db: Session, note_id: UUID) -> Optional[PublishedIdea]:
    return db.get(PublishedIdea, note_id)


def publish(db: Session, user_id: UUID, idea: Idea) -> PublishedIdea:
    check_publishable(idea)
    token, chat = _ready(db)
    existing = get_published(db, idea.note_id)
    if existing is not None and existing.unpublished_at is None:
        raise IdeaError(409, "This note is already published. Unpublish it first to post it again.")
    plan = plan_post(idea)

    sent: list[int] = []
    for kind, body in plan.messages:
        result = telegram_api.send_photo(token, chat, idea.image, body) if kind == "photo" else telegram_api.send_message(token, chat, body)
        if not result.ok or result.message_id is None:
            for mid in sent:  # do not leave half a post in the channel
                telegram_api.delete_message(token, chat, mid)
            raise IdeaError(502, f"Could not post: {result.error or 'no message id returned'}.")
        sent.append(result.message_id)

    row = existing or PublishedIdea(note_id=idea.note_id)
    row.published_by, row.chat_id, row.message_ids, row.text = user_id, chat, sent, plan.text
    row.has_image = idea.image is not None
    row.published_at, row.unpublished_at = datetime.now(timezone.utc), None
    db.add(row)
    db.commit()
    return row


def unpublish(db: Session, note_id: UUID, force: bool = False) -> PublishedIdea:
    """Delete the post from the channel and mark it unpublished. Telegram only lets a bot delete its messages for a limited time
    (about 48 hours); when it refuses, `force` records it as unpublished anyway so the person can delete the message by hand."""
    row = get_published(db, note_id)
    if row is None or row.unpublished_at is not None:
        raise IdeaError(404, "This note is not published.")
    token = settings.telegram_ideas_bot_token
    if not token:
        raise IdeaError(503, "The ideas bot is not set up on this server (TELEGRAM_IDEAS_BOT_TOKEN).")
    failures = [r.error for mid in row.message_ids if not (r := telegram_api.delete_message(token, row.chat_id, mid)).ok]
    if failures and not force:
        raise IdeaError(409, f"Telegram would not delete it ({failures[0]}). If it is old, delete it in Telegram yourself, then mark it unpublished here.")
    row.unpublished_at = datetime.now(timezone.utc)
    db.commit()
    return row
